authors:
- Parameswaran Krishnamurthy <Parameswaran_Krishna@Dell.com>
- Senthil Ganesan Ganesan <Senthil_Kumar_Ganesa@Dell.com>
- Shreeja R <Shreeja_R@Dell.com>
dependencies:
  ansible.netcommon: '>=0.0.1'
description: Ansible collections for Dell EMC PowerSwitch platforms running Dell EMC SmartFabric OS10
license_file: LICENSE
name: os10
namespace: dellemc_networking
readme: README.md
tags: [dell, dellemc, os10, emc, networking]
version: 1.0.1
repository: https://github.com/ansible-collections/dellemc_networking.os10
documentation: https://github.com/ansible-collections/dellemc_networking.os10/tree/master/docs
homepage: https://github.com/ansible-collections/dellemc_networking.os10
issues: https://github.com/ansible-collections/dellemc_networking.os10/issues
