authors: Parameswaran Krishnamurthy, Senthil Ganesan, Shreeja R
dependencies:
  ansible.netcommon: '>=0.0.1'
description: Ansible collections for Dell EMC PowerSwitch platforms running Dell EMC SmartFabric OS10
license_file: LICENSE
name: os10
namespace: dellemc_networking
readme: README.md
tags: dell dellemc os10 emc networking
version: 0.0.9
repository: https://github.com:ansible-collections/dellemc_networking.os10.git
documentation: https://github.com/ansible-collections/dellemc_networking.os10/docs
homepage: https://github.com:ansible-collections/dellemc_networking.os10
issues: https://github.com:ansible-collections/dellemc_networking.os10
